spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/top3
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
